### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by lukesneeringer** [chrisbuttery/duo-react#1]
I came across this repository through [this issue](https://github.com/duojs/test/issues/55); I have been having a similar problem with PhantomJS' not having `Function.prototype.bind`.

Is it okay if I copy your polyfill flat out? This repository does not include a license so I wanted to ask first.

**Comment by chrisbuttery** [comment]
Hi @lukesneeringer, Thanks for asking. This sandbox is actually using the shim I borrowed from facebook a fair while back.
I should really update it to use this polyfill.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill
